name: Release
on:
 push:
  branches:
    - master

jobs:
 release:
  runs-on: ubuntu-latest

  steps:
    - name: Checkout Code
      uses: actions/checkout@v3
 
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.12.2'

    - name: Install Dependencies
      run: npm install
 
    - name: Build Library
      run: npm run build

    - name: Authenticate with npm
      run: npm login --registry=https://registry.npmjs.org/ --scope=public --json
      env:
       NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Publish to npm
      if: github.ref == 'refs/heads/master'
      run: npm publish --access public
      env:
       NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
       MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Create GitHub Release
      if: github.ref == 'refs/heads/master'
      uses: actions/create-release@v1
      with:
       tag_name: ${{ github.sha }}
       release_name: Release ${{ github.sha }}
       body: |
        This release was created by GitHub Actions Workflows.
       draft: false
       prerelease: false
      env:
       MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
