name: Release
on:
 push:
  branches:
    - master

jobs:
 release:
  runs-on: ubuntu-latest

  steps:
    - name: Checkout Code
      uses: actions/checkout@v3
 
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.12.2'

    - name: Install Dependencies
      run: npm install
 
    - name: Build Library
      run: npm run build

    - name: Get last version
      id: get_version
      run: |
       VERSION=$(node -p "require('./package.json').version")
       echo "VERSION=$VERSION" >> $GITHUB_ENV
       echo "Version found in package.json: $VERSION"

    - name: Set up .npmrc
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

    - name: Debug npm auth
      run: npm whoami

    - name: Publish to npm
      if: github.ref == 'refs/heads/master'
      run: npm publish --access public
      env:
       NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Create GitHub Release
      if: github.ref == 'refs/heads/master'
      uses: actions/gh-release@v2
      with:
       name: ${{ env.VERSION }}
       tag_name: ${{ env.VERSION }}
       body: |
        This release was created by GitHub Actions Workflows.
       draft: false
       prerelease: false
      env:
       GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
